### ISSUE TITLE
Possible Bottleneck PyPDFium2

### ISSUE THREAD

**Issue by AndiKarg** [VikParuchuri/marker#155]
PyPDFium2 doesnt work for my use cases as i have a lot of pdfs with fillable fields...

Is it possible to make the PDF Library variable?
From my expertise PyMUPDF looks like the best out here so maybe this can further improve your results.

I think its definetly worth a shot.

**Comment by VikParuchuri** [comment]
Marker v1 used pymupdf, but it is unfortunately AGPL-licensed, so I removed it for newer versions.  If you use an older version of marker (use an older git commit and manually install) you can use pymupdf.

**Comment by yasyf** [comment]
@VikParuchuri maybe an option to use pymupdf as an optional dependency, if it's not too much work to support both codepaths?

**Comment by mara004** [comment]
> PyPDFium2 doesnt work for my use cases as i have a lot of pdfs with fillable fields...

@AndiKarg I'm maintainer of pypdfium2. "doesn't work for [...] pdfs with fillable fields" is a bit vague. Can give an example, or point out where we are lacking APIs compared to pymupdf?
If the issue is text of form fields not being extracted, an option to flatten forms into page contents using pdfium's `FPDFPage_Flatten()` was recently added to `pdftext`. Is that what you are looking for?

**Comment by AndiKarg** [comment]
Yes PDF flatten is exactly what i been looking for! Thanks
