### ISSUE TITLE
"Tables are not always formatted 100% correctly"

### ISSUE THREAD

**Issue by Terranic** [VikParuchuri/marker#204]
Observing this issue very often when converting. Are there any ways to improve correct table translations? 
Wrong text within cells makes the md hardly usable

Here is an example, I know that the table is not the easiest, but some other tables face the same problem.

pdf
![image](https://github.com/VikParuchuri/marker/assets/59094334/e257e9c4-2f4e-4d48-b365-c69284e17326)
[table.pdf](https://github.com/user-attachments/files/15966980/table.pdf)

converted

![image](https://github.com/VikParuchuri/marker/assets/59094334/5b6c040c-e735-4dd3-8454-4560188f9fc7)

The "hard" problem is that "Accuracy" is now in the wrong column.

**Comment by kksasa** [comment]
faced same issue too

**Comment by tonkatsu7** [comment]
similar... trying to find ways to get another completion to fix the errors if there is a spec

1. PDF https://www.finance.gov.au/sites/default/files/2023-05/portfolio-budget-statements-2023-24.pdf 
![image](https://github.com/VikParuchuri/marker/assets/20418201/d65c49e3-431b-42d5-b760-e8b9a79d9553)

2. Converted markdown: 
## 1.3 Budget Measures

Budget measures in Part 1 relating to Finance are detailed in the Budget Paper No. 2 and are summarised below.

| Table 1.2: Department of Finance 2023-24 Budget measures Part 1: Measures announced since the 2022-23 October Budget 2022-23 2023-24 2024-25   | 2025-26        | 2026-27   |       |        |       |        |       |        |       |        |
|------------------------------------------------------------------------------------------------------------------------------------------------|----------------|-----------|-------|--------|-------|--------|-------|--------|-------|--------|
| Program                                                                                                                                        | $'000          | $'000     | $'000 | $'000  | $'000 |        |       |        |       |        |
| Receipt measures Buy Australian Plan (a)                                                                                                       |                | 2.5       |       |        |       |        |       |        |       |        |
| Departmental receipt                                                                                                                           |                | -         |       | 6,588  |       | 3,957  |       | 4,745  |       | 2,852  |
| Securing a Unique and Critical Defence Capability (b)                                                                                          |                | 2.1       |       |        |       |        |       |        |       |        |
| Administered receipt                                                                                                                           |                | -         | nfp   | nfp    | nfp   | nfp    |       |        |       |        |
| Total                                                                                                                                          | -              |           | 6,588 |        | 3,957 |        | 4,745 |        | 2,852 |        |
| Total receipt measures Administered                                                                                                            |                | -         | nfp   | nfp    | nfp   | nfp    |       |        |       |        |
| Departmental                                                                                                                                   |                | -         |       | 6,588  |       | 3,957  |       | 4,745  |       | 2,852  |
| Total                                                                                                                                          |                | -         |       | 6,588  |       | 3,957  |       | 4,745  |       | 2,852  |
| Payment measures APS Capability Reinvestment Fund: 2023-24 projects  funded under round one (c)                                                |                | 2.1       |       |        |       |        |       |        |       |        |
| Departmental payment                                                                                                                           |                | -         |       | 20     |       | -      |       | -      |       | -      |
| Big Data, Timely Insights Phase 2 - securing Australia's                                                                                       |                | 2.1       |       |        |       |        |       |        |       |        |
| critical economic data and supporting better informed  macroeconomic policy (d) Departmental payment                                           |                | -         |       | 100    |       | 100    |       | -      |       | -      |
| Buy Australian Plan (a)                                                                                                                        |                | 2.5       |       |        |       |        |       |        |       |        |
| Departmental payment                                                                                                                           |                | -         |       | 6,588  |       | 3,957  |       | 4,745  |       | 2,852  |
| tranche) (e)                                                                                                                                   |                | 2.1       |       |        |       |        |       |        |       |        |
| Electoral Commission - critical ICT replacement (second  Departmental payment                                                                  |                | -         |       | 105    |       | -      |       | 185    |       | 187    |
| Establish the Australian Centre for Disease Control (f)                                                                                        |                | 2.1       |       |        |       |        |       |        |       |        |
| Departmental payment                                                                                                                           |                | -         |       | 135    |       | 135    |       | -      |       | -      |
| Finance Portfolio - additional resourcing (g)                                                                                                  | 1.1, 2.1,  3.1 |           |       |        |       |        |       |        |       |        |
| Departmental payment                                                                                                                           |                | -         |       | 17,963 |       | 12,296 |       | 12,415 |       | 12,527 |
| minimum tax (h)                                                                                                                                |                | 2.1       |       |        |       |        |       |        |       |        |
| Implementation of a global minimum tax and a domestic  Departmental payment                                                                    |                | -         |       | 135    |       | 135    |       | 135    |       | 135    |
| Implementing Aged Care Reform - home care (i)                                                                                                  |                | 2.1       |       |        |       |        |       |        |       |        |
| Departmental payment                                                                                                                           |                | -         |       | 72     |       | -      |       | -      |       | -      |
| Improving the Administration of Student Loans (j)                                                                                              |                | 2.1       |       |        |       |        |       |        |       |        |
| Departmental payment                                                                                                                           |                | -         |       | 150    |       | 150    |       | 100    |       | -      |
| Improving the Culture of Parliamentary Workplaces (k)                                                                                          |                | 3.1       |       |        |       |        |       |        |       |        |
| Departmental payment                                                                                                                           |                | -         |       | 16,687 |       | 12,706 |       | 11,554 |       | 12,418 |
| National Disability Insurance Scheme (l)                                                                                                       |                | 2.1       |       |        |       |        |       |        |       |        |
| Improving the Effectiveness and Sustainability of the  Departmental payment                                                                    |                | -         |       | 135    |       | -      |       | -      |       | -      |
| Modernisation and Sustainment of ICT Systems (m)                                                                                               |                | 2.1       |       |        |       |        |       |        |       |        |
| Departmental payment                                                                                                                           |                | -         |       | 100    |       | 100    |       | 100    |       | 100    |
| Next Steps for Digital ID (n)                                                                                                                  |                | 2.1       |       |        |       |        |       |        |       |        |
| Departmental payment                                                                                                                           |                | -         |       | 10,030 |       | -      |       | -      |       | -      |
| Table continues on next page                                                                                                                   |                |           |       |        |       |        |       |        |       |        |

3. PDF spec (in PDF) https://www.finance.gov.au/sites/default/files/2024-03/guide-to-preparing-the-2024-25-portfolio-budget-statements.pdf
![image](https://github.com/VikParuchuri/marker/assets/20418201/5a7da117-19a8-496c-8f06-cd0dc37327fa)

**Comment by 0x01111** [comment]
similar...

**Comment by VikParuchuri** [comment]
Should be fixed now
