### ISSUE TITLE
supporting Chinese

### ISSUE THREAD

**Issue by songge25** [VikParuchuri/marker#25]
wonderful work！
Would you consider supporting Chinese in later？

**Comment by VikParuchuri** [comment]
Yes, this is on my list.  In order to do this, I will need to:

- Train an OCR gibberish detector model (to replace current spelling heuristics)
- Understand Chinese grammar enough to make sure all the heuristics make sense (or find someone to test)
- Retrain some of the models to incorporate multilingual training data
- Find someone to test end to end
